rvm:
  - 1.9
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - ruby-head
  - rbx-3.69
  - jruby-9.1.14.0
  - jruby
  - jruby-head

install:
  - ruby -S gem install bundler --version 1.15.4
  - ruby -S bundle _1.15.4_ install --without docs

script:
  - ruby -S bundle _1.15.4_ exec rspec

sudo: false

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby
    - rvm: jruby-head
    - rvm: rbx-3.69
    - rvm: 2.4 # https://bugs.ruby-lang.org/issues/13537

notifications:
  irc: "irc.freenode.org#pry"
  recipients:
    - jrmair@gmail.com

branches:
  only:
    - master
